### PR TITLE
fix(security): bump major versions from passport-saml and uuid

### LINKED ISSUE #146: uuid dependency outdated
uuid dependency is outdated. Please check major/breaking changes carefully.

### PR DESCRIPTION
**Pull request by christian-hawk**
**Important**: review/merge this PR after reviewing/mergint #149 

close #146 #148

### CODE REVIEW

File: server/utils/logging.js [hunk 1]
```diff
@@ -6,9 +6,11 @@ const util = require('util')
 const R = require('ramda')
 const misc = require('./misc')
 const format = winston.format
+const path = require('path')
+
+const dir = R.defaultTo(
+  path.join(__dirname, 'logs'), process.env.NODE_LOGGING_DIR)
```
Comment (kdhttps) [inline server/utils/logging.js:12]: what you think to use vallina js here instead on ramda? If yes then we should refactor this at every place.

**Review by kdhttps — CHANGES_REQUESTED** [review]
@christian-hawk requested for little change. also need to update branch with base branch

File: server/utils/logging.js (hunk 1 above)
Comment (christian-hawk) [reply server/utils/logging.js]: Good idea mate, thanks!
so for `R.defaultTo` I created a helper function in `misc.js` and replaced all `R.defaultTo` in `logging.js`

If you want feel free to raise an issue to refactor all R.defaultTo, I may take care of it.

Thanks for the good review.

File: server/utils/logging.js [hunk 2]
```diff
@@ -8,8 +8,9 @@ const misc = require('./misc')
 const format = winston.format
 const path = require('path')
 
-const dir = R.defaultTo(
-  path.join(__dirname, 'logs'), process.env.NODE_LOGGING_DIR)
+const dir = misc.assignDefaultValueIfUnexistant(
+  path.join(__dirname, 'logs'), process.env.NODE_LOGGING_DIR
+)
```
Comment (kdhttps) [inline server/utils/logging.js:13]: @christian-hawk mate, I think we can easily handle this using `||` operator, no need for extra function
for example:
Instead of above code, we can do this like
```
const dir = process.env.NODE_LOGGING_DIR || path.join(__dirname, 'logs')
```
second value is default value here.

File: server/utils/logging.js [hunk 3]
```diff
@@ -132,7 +134,9 @@ function log2 (level, msg) {
   level = level.toLowerCase()
   level = R.includes(level, levels) ? level : 'info'
 
-  msg = R.defaultTo('', msg)
+  if (!msg && msg !== '') {
+    msg = ''
+  }
```
Comment (kdhttps) [inline server/utils/logging.js:139]: here its like `msg = msg || '' `

**Review by kdhttps — CHANGES_REQUESTED** [review]

File: server/utils/logging.js (hunk 2 above)
Comment (christian-hawk) [reply server/utils/logging.js:13]: Didn't knew about logical OR `||` operator on JS. thank you so much for that 👍🏻 I learn everyday w/ u.

So `R.defaultTo` is totally useless when uncurried!
Wish I knew this before ahahahah

**Review by kdhttps — APPROVED** [review]
